### ISSUE TITLE
Aero for Crystal Language

### ISSUE THREAD

**Issue by ansarizafar** [aerogo/aero#1]
Crystal Language http://crystal-lang.org/ is faster, better and simpler than Go. The only missing thing is parallelism which the core team is working on. I would request you to take a look and If possible develop Aero in Crystal Language.

**Comment by blitzprog** [comment]
This is not an Aero Go related issue.

**Comment by blitzprog** [comment]
P.S. Go has brilliant tools as an addition to the language. Performance also depends on implementations. **Never** trust someone else's benchmarks.

Even if the implementation that was benchmarked is faster, in 99.9% of cases the router is not the bottleneck of a web app. Go is fast enough due to being a compiled language.
